### ISSUE TITLE
Create initial version of theme

### ISSUE THREAD

**Issue by ghing** [ghing/geoff-wordpress-theme#1]
## Tasks

* [x] Start with Timber Starter Theme
* [ ] Style homepage posts
* [ ] Style footer
* [ ] Fix collapsing navbar menu
